# Generated by Django 3.2.10 on 2021-12-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_pic',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party_logo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
