# Generated by Django 3.2.10 on 2022-01-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211209_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredvoters',
            name='otp',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
