# Generated by Django 3.2.10 on 2022-01-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_registeredvoters_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredvoters',
            name='account_verified',
            field=models.BooleanField(default=False),
        ),
    ]
