# Generated by Django 3.2.10 on 2022-03-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_constituency'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredvoters',
            name='c_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uniqueid',
            name='c_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
