# Generated by Django 3.2.10 on 2022-03-27 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220327_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='party_logo',
        ),
    ]
