# Generated by Django 3.2.10 on 2022-06-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220328_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredvoters',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='uniqueid',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
